### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by nochinsky** [Phew/angst-rewrite#4]
I get this error when I run the exe file after compiling with pyinstaller 
https://iam.unhittable.cc/🍯🚝🍩🔍😅

**Comment by HectorsGrav3** [comment]
iam stupid i didnt attack the file
![WindowsTerminal_8CQZHu6Aqn](https://github.com/Phew/angst-rewrite/assets/103116639/d55d7b38-9204-4ac3-a8a1-83925bf4d303)

**Comment by nochinsky** [comment]
Forgot to upload the file and uploaded it to the link accidentaly

![WindowsTerminal_8CQZHu6Aqn](https://github.com/Phew/angst-rewrite/assets/103116639/20b05793-3d07-40e5-9c7f-be27dc4333fe)

**Comment by Phew** [comment]
Should be fixed, download again and rebuild
